image:
  repository: sknnr/soulmask-dedicated-server
  pullPolicy: IfNotPresent
  tag: v1.1.3@sha256:0484fcdbe4f50e31824104caa53df1f11401c24a133749ccd611a8fef2f99e32
persistence:
  data:
    enabled: true
    mountPath: /home/steam/soulmask
service:
  main:
    type: LoadBalancer
    ports:
      main:
        enabled: true
        port: 18888
        protocol: tcp
      game:
        enabled: true
        port: 27020
        protocol: udp
      query:
        enabled: true
        port: 27015
        protocol: udp
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FORCE_UPDATE: false
            LEVEL_NAME: Level01_Main
            GAME_PORT: 27020
            QUERY_PORT: 27015
            ECHO_PORT: 18888
            MAX_PLAYERS: 10
            SERVER_NAME: "Dodgeball Time"
            SAVED_DIR_SUFFIX: 
            SERVER_PASSWORD: S0ulm4sk
            ADMIN_PASSWORD: changeme
            INIT_BACKUP: true
            BACKUP_INTERVAL_MINUTES: 30
            SAVING_SYNC_INTERVAL_SECONDS: 120
            BACKUP_SYNC_INTERVAL_SECONDS: 120
            GAME_MODE: pve
            MOD_ID_LIST:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false                
